[options]
; La contraseña maestra para crear o borrar bases de datos desde la web
admin_passwd = GoCloud_Serv_2025

; Conexión a tu contenedor de base de datos
db_host = db_vortex
db_port = 5432
db_user = odoo
db_password = odoo

; Configuraciones de rendimiento básicas
limit_time_cpu = 600
limit_time_real = 1200